# Generated by Django 6.0.5 on 2026-05-25 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutiques', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='avis',
            old_name='boutique',
            new_name='boutiques',
        ),
        migrations.RenameField(
            model_name='avis',
            old_name='commentaire',
            new_name='commentaires',
        ),
        migrations.RenameField(
            model_name='avis',
            old_name='date',
            new_name='dates',
        ),
        migrations.RenameField(
            model_name='avis',
            old_name='note',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='avis',
            old_name='utilisateur',
            new_name='utilisateurs',
        ),
        migrations.AlterField(
            model_name='boutique',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='boutiques/'),
        ),
        migrations.CreateModel(
            name='AvisBoutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('commentaire', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_boutique', to='boutiques.boutique')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
