# Generated by Django 6.0.5 on 2026-06-18 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutiques', '0002_rename_boutique_avis_boutiques_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avis',
        ),
    ]
