# Generated by Django 6.0.5 on 2026-07-07 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetailCommande',
        ),
    ]
