# Generated by Django 6.0.5 on 2026-07-07 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutiques', '0004_contrainte_avis_boutique'),
        ('commandes', '0003_rename_date_creation_commande_date_commande_and_more'),
        ('produits', '0006_infos_credibilite_produit'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_vente', models.DateTimeField(auto_now_add=True)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boutiques.boutique')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commandes.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.produit')),
            ],
        ),
    ]
