# Generated by Django 6.0.5 on 2026-07-07 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0004_historiquevente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='montant_total',
            new_name='total',
        ),
    ]
