# Generated by Django 6.0.5 on 2026-07-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0005_rename_montant_total_commande_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='total',
            new_name='montant_total',
        ),
        migrations.AddField(
            model_name='historiquevente',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=12),
            preserve_default=False,
        ),
    ]
