# Generated by Django 6.0.5 on 2026-07-07 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutiques', '0004_contrainte_avis_boutique'),
        ('commandes', '0006_rename_total_commande_montant_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiquevente',
            name='boutique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_ventes', to='boutiques.boutique'),
        ),
        migrations.AlterField(
            model_name='historiquevente',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_ventes', to='commandes.commande'),
        ),
    ]
