# Generated by Django 6.0.5 on 2026-07-08 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0007_alter_historiquevente_boutique_and_more'),
        ('paiements', '0003_paiement_numero_telephone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiquevente',
            name='paiement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paiements.paiement'),
        ),
    ]
