# Generated by Django 6.0.5 on 2026-07-07 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0003_rename_date_creation_commande_date_commande_and_more'),
        ('paiements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiement',
            name='commande_id',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='status',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='utilisateur',
        ),
        migrations.AddField(
            model_name='paiement',
            name='commande',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='commandes.commande'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paiement',
            name='date_paiement',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paiement',
            name='reference',
            field=models.CharField(default=None, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('attente', 'En attente'), ('valide', 'Validé'), ('echec', 'Échec')], default='attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='methode',
            field=models.CharField(choices=[('orange', 'Orange Money'), ('airtel', 'Airtel Money'), ('mpesa', 'M-Pesa')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
