# Generated by Django 6.0.5 on 2026-07-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0002_remove_paiement_commande_id_remove_paiement_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='numero_telephone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='paiement',
            name='reference_transaction',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
