# Generated by Django 6.0.5 on 2026-05-21 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutiques', '0001_initial'),
        ('comparateur', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparaison',
            name='boutique_nom',
        ),
        migrations.AddField(
            model_name='comparaison',
            name='boutique',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='boutiques.boutique'),
            preserve_default=False,
        ),
    ]
