# Generated by Django 6.0.5 on 2026-05-25 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type_user',
            field=models.CharField(choices=[('client', 'Client'), ('vendeur', 'Vendeur'), ('visiteur', 'Visiteur')], default='client', max_length=20),
        ),
    ]
