# Generated by Django 6.0.5 on 2026-07-07 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lignepanier',
            name='prix_unitaire',
        ),
    ]
