# Generated by Django 6.0.5 on 2026-06-18 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0004_categorie_produit_categorie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Panier',
        ),
    ]
